#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT_FACE="JetBrainsMono Nerd Font"
PADDINGS=3 # All paddings use this value (icon, label, background)
BAR_PADDINGS=5
BORDER_WIDTH_1=0

# Setting up the general bar appearance of the bar
bar=(
  position=top
  height=38
  blur_radius=40
  color=0x40000000
  topmost=window
  sticky=on
  font_smoothing=true
  notch_width=188
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:17.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$BAR_PADDINGS
  padding_left=$BAR_PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Spotify
# sketchybar --add event spotify_change $SPOTIFY_EVENT \
#     --add item spotify e \
#     --set spotify \
#     icon= \
#     background.color=$BACKGROUND_1 \
#     icon.y_offset=1 \
#     icon.padding_left=5 \
#     icon.padding_right=5 \
#     label.font="$FONT_FACE:Regular:14.0" \
#     icon.font="$FONT_FACE:Bold:20.0" \
#     label.drawing=off \
#     label.padding_left=3 \
#     label.padding_right=10 \
#     script="$PLUGIN_DIR/spotify.sh" \
#     --subscribe spotify spotify_change mouse.clicked


# sketchybar --add item weather.moon q \
#     --set weather.moon \
#     background.color=0x667dc4e4 \
#     background.padding_right=-1 \
#     icon.color=0xff181926 \
#     icon.font="$FONT_FACE:Bold:22.0" \
#     icon.padding_left=10 \
#     icon.padding_right=10 \
#     label.drawing=off \
#     --subscribe weather.moon mouse.clicked
#
# sketchybar --add item weather q \
#     --set weather \
#     icon= \
#     icon.color=0xfff5bde6 \
#     icon.font="$FONT_FACE:Bold:15.0" \
#     label.font="$FONT_FACE:Regular:14.0" \
#     background.color=$BACKGROUND_1 \
#     icon.y_offset=1 \
#     label.y_offset=1 \
#     update_freq=1800 \
#     script="$PLUGIN_DIR/weather.sh" \
#     icon.padding_left=10 \
#     icon.padding_right=10 \
#     label.padding_right=10 \
#     label.padding_left=0 \
#     label.drawing=off \
#     --subscribe weather system_woke

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
