#!/bin/bash

source "$HOME/.config/borders/colors.sh"

options=(
    style=round
    width=6
    hidpi=on
    active_color="gradient(top_left=0xee$MOCHA_LAVENDER,bottom_right=0xee$MOCHA_MAUVE)"
    inactive_color="gradient(top_left=0xaa$MOCHA_OVERLAY0,bottom_right=0xdd$MOCHA_SURFACE0)"
    order=below
    ax_focus=on
)

borders "${options[@]}"
