#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons
source "$HOME/.config/sketchybar/fonts.sh"

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

PADDINGS=3 # All paddings use this value (icon, label, background)
BAR_PADDINGS=5
BORDER_WIDTH_1=0

# Setting up the general bar appearance of the bar
bar=(
    position=top
    height=40
    blur_radius=25
    color=$BAR_COLOR
    topmost=window
    sticky=on
    font_smoothing=true
    notch_width=188
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
    updates=when_shown
    icon.font="$FONT:Bold:17.0"
    icon.color=$ICON_COLOR
    icon.padding_left=$PADDINGS
    icon.padding_right=$PADDINGS
    label.font="$FONT:Semibold:14.0"
    label.color=$LABEL_COLOR
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
    padding_right=$BAR_PADDINGS
    padding_left=$BAR_PADDINGS
    background.height=30
    background.corner_radius=9
    popup.background.border_width=2
    popup.background.corner_radius=9
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.blur_radius=20
    popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
